### ISSUE TITLE
Shared Folder.

### ISSUE THREAD

**Issue by CrackerakiUA** [g33kidd/node-dropbox#8]
How can we create a shared folder between two users?

**Comment by g33kidd** [comment]
I don't think this is possible with the Dropbox API at the moment. Although you can create 'share links' for a folder or files. https://www.dropbox.com/developers-v1/core/docs#shares

Unless I've missed something in the API docs, please do let me know if this is possible.

**Comment by CrackerakiUA** [comment]
I did check, you are correct.
